name: Linter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: run linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GIHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}